import RootLayout from "../components/layout/root-layout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <RootLayout menuItems={[]}>{children}</RootLayout>;
}
